name: tests
permissions:
  contents: read
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        go-version: [ "1.22", "1.23" ]
    runs-on: ubuntu-latest
    steps:
      - name: Setup go environment
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run go test
        run: scripts/test.sh
